### PR TITLE
Enable Mirage2 theme

### PR DESCRIPTION
**Pull request by keithgee**
This is an adaptive theme from @mire based on bootstrap.

### CODE REVIEW

**Comment by keithgee** [comment]
I'm hoping this mirage2 theme will at least give us a more modern look until Chris is available to work on the major interface overhaul.

This theme doesn't build correctly with the latest version of maven 3.3.3 that we've all installed with home-brew, which will make the repository look like it's missing a style sheet.  I'll soon post instructions in the README file of the vtlibans_dspace project on how to install the correct version (3.2.5)  of maven.

**Comment by amandafrench** [comment]
FYI, @keithgee, at some point you mentioned that it was too easy to commit to the core dSpace repo -- I changed the name of this repo to amandafrench/VT-DSpace in hopes that makes the distinction a bit clearer. Not sure if that might cause issues for code as well as for documentation ...

**Comment by kayiwa** [comment]
Hey @keithgee is the maven 3.2.5 an OSX (going to test this) or will the dev/preprod and prod also need this?

**Comment by keithgee** [comment]
It's a requirement for all systems; the Mirage2 theme build process is
incompatible with Maven 3.3.x.

**Comment by keithgee** [comment]
Though, Francis, I'm not sure yet how dev/preprod/prod installs will happen. If these installs will require Maven, we need the 3.2.5 version.

**Comment by keithgee** [comment]
@amandafrench that shouldn't cause any code issues but we'll test and keep watch

**Pull request merged**
